dist: xenial

jobs:
  include:
    - language: node_js
      node_js: 14
      cache: npm
      script:
      - cd frontend
      - npm install -g @angular/cli

    - language: java
      jdk:
      - oraclejdk16
      cache:
        directories:
        - $HOME/.m2
      script:
      - cd backend
      - sonar-scanner -Dsonar.projectKey=brendo10x_desafio-dev
addons:
  sonarcloud:
    organization: "brendo10x"
    token:
      secure: ${SONAR_TOKEN}