sudo: required
dist: xenial

jobs:
  include:
    - language: node_js
      node_js: 14
      cache: npm
      script:
      - cd frontend
      - npm install -g @angular/cli
      - sonar-scanner
      addons:
        sonarcloud:
          organization: "brendo10x"
          token:
            secure: "636975d39c7874fd31732421e580098f29f3a196"

    - language: java
      jdk:
      - oraclejdk16
      cache:
        directories:
        - $HOME/.m2
        - $HOME/.sonar/cache
      script:
      - cd backend
      - mvn install -DskipTests=true