sudo: required
dist: xenial

jobs:
  include:
    - language: node_js
      node_js: 14
      cache: npm
      script:
      - cd frontend
      - npm install -g @angular/cli

    - language: java
      jdk:
      - oraclejdk16
      cache:
        directories:
        - $HOME/.m2
        - $HOME/.sonar/cache
      addons:
        sonarcloud:
          organization: "brendo10x"
          token:
            secure: "423b291f433fae06a9a6416dfbdbdf76637d8210"
      script:
      - cd backend
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=brendo10x_desafio-dev -DskipTests=true